# Generated by Django 5.1.6 on 2025-02-17 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_room_created_room_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['updated', 'created']},
        ),
    ]
